type: zs_one_pass
prompt_name: ego4d
history_levels: 0
include_lowest_level_details: True  # The agent approaches also receive these details
llm:
  type: ChatGoogleGenerativeAI
  model: gemini-1.5-pro
  max_tokens: 512
  temperature: 0.1
  request_timeout: 40
  max_retries: 2
prompt_cfg: null
